package main

import (
	"fmt"
	"net/http"
)

func main() {
	// Serve static files from the "build" directory (generated by React build)
	fs := http.FileServer(http.Dir("../build"))
	http.Handle("/", fs)

	// Handle all requests by serving the index.html file
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "../build/index.html")
	})

	fmt.Println("Server is listening on port 8080...")
	if err := http.ListenAndServe(":8080", nil); err != nil {
		fmt.Printf("Error starting server: %s\n", err)
	}
}
